name: Check for push1
on:
    workflow_dispatch:
    push:
        branches: [ main ]

    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#       - name: script
#         run: |
#              echo "Hello!! running 2nd workflow"
#              curl -X POST https://api.github.com/repos/vijeths/repoB/actions/workflows/check.yml/dispatches \
#                   -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
#                   -H "Accept application/vnd.github.v3+json" \
#                   -d '{"ref":"main"}'
                  
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_PAT }}
          repository: vijeths/repoB
          event-type: my-event(triggered in repository ${{ github.repository }} by  ${{ github.actor }})
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
