name: Check for push
on:

  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: script
        run: |
             echo "Hello!! running 2nd workflow"
             
             
